[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { eth = "https://eth-sepolia.g.alchemy.com/v2/30JvLqAynClpckAFpG18G", arb = "https://arb-sepolia.g.alchemy.com/v2/30JvLqAynClpckAFpG18G" }

remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/contracts/',
    '@ccip/=lib/ccip/contracts/src/v0.8/',
    '@chainlink-local/=lib/chainlink-local/src',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
